In [22]:
%run C:/Raj/ML/Python/nuevo_projecto/notebooks/modules.ipynb

In [23]:
df = pd.read_csv("C:/Raj/ML/Python/nuevo_projecto/dataset/crx.data")

In [24]:
df.head()

   b  30.83      0  u  g  w  v  1.25  t t.1  01  f g.1  00202  0.1  +
0  a  58.67  4.460  u  g  q  h  3.04  t   t   6  f   g  00043  560  +
1  a  24.50  0.500  u  g  q  h  1.50  t   f   0  f   g  00280  824  +
2  b  27.83  1.540  u  g  w  v  3.75  t   t   5  t   g  00100    3  +
3  b  20.17  5.625  u  g  w  v  1.71  t   f   0  f   s  00120    0  +
4  b  32.08  4.000  u  g  m  v  2.50  t   f   0  t   g  00360    0  +

In [25]:
columns = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P']
df = pd.read_csv("C:/Raj/ML/Python/nuevo_projecto/dataset/crx.data", names = columns)
df

     A      B       C  D  E   F   G     H  I  J  K  L  M      N    O  P
0    b  30.83   0.000  u  g   w   v  1.25  t  t  1  f  g  00202    0  +
1    a  58.67   4.460  u  g   q   h  3.04  t  t  6  f  g  00043  560  +
2    a  24.50   0.500  u  g   q   h  1.50  t  f  0  f  g  00280  824  +
3    b  27.83   1.540  u  g   w   v  3.75  t  t  5  t  g  00100    3  +
4    b  20.17   5.625  u  g   w   v  1.71  t  f  0  f  s  00120    0  +
..  ..    ...     ... .. ..  ..  ..   ... .. .. .. .. ..    ...  ... ..
685  b  21.08  10.085  y  p   e   h  1.25  f  f  0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.00  f  t  2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.00  f  t  1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.04  f  f  0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.29  f  f  0  t  g  00000    0  -

[690 rows x 16 columns]